const mockCollections = [
    {
      id: 1,
      name: 'Art 01',
      summary: 'A stunning collection of digital art pieces.',
      price: 100,
      category: 'Art',
      imageUrl: 'https://picsum.photos/id/641/367/267',
    },
    {
      id: 2,
      name: 'Music 01',
      summary: 'An eclectic variety of digital music tracks.',
      price: 50,
      category: 'Music',
      imageUrl: 'https://picsum.photos/id/145/367/267',
    },
    {
      id: 3,
      name: 'Fashion 01',
      summary: 'Discover the latest in digital fashion trends.',
      price: 80,
      category: 'Fashion',
      imageUrl: 'https://picsum.photos/id/758/367/267',
    },
    {
      id: 4,
      name: 'Art 02',
      summary: 'A stunning collection of digital art pieces.',
      price: 120,
      category: 'Art',
      imageUrl: 'https://picsum.photos/id/641/367/267',
    },
    {
      id: 5,
      name: 'Music 02',
      summary: 'An eclectic variety of digital music tracks.',
      price: 40,
      category: 'Music',
      imageUrl: 'https://picsum.photos/id/145/367/267',
    },
    {
      id: 6,
      name: 'Fashion 02',
      summary: 'Discover the latest in digital fashion trends.',
      price: 90,
      category: 'Fashion',
      imageUrl: 'https://picsum.photos/id/758/367/267',
    },
    {
      id: 7,
      name: 'Art 03',
      summary: 'A stunning collection of digital art pieces.',
      price: 150,
      category: 'Art',
      imageUrl: 'https://picsum.photos/id/641/367/267',
    },
    {
      id: 8,
      name: 'Music 03',
      summary: 'An eclectic variety of digital music tracks.',
      price: 35,
      category: 'Music',
      imageUrl: 'https://picsum.photos/id/145/367/267',
    },
    {
      id: 9,
      name: 'Fashion 03',
      summary: 'Discover the latest in digital fashion trends.',
      price: 95,
      category: 'Fashion',
      imageUrl: 'https://picsum.photos/id/758/367/267',
    },
    {
      id: 10,
      name: 'Art 04',
      summary: 'A stunning collection of digital art pieces.',
      price: 130,
      category: 'Art',
      imageUrl: 'https://picsum.photos/id/641/367/267',
    },
  ];

  export default mockCollections;